### ISSUE TITLE
import session

### ISSUE THREAD

**Issue by juliomateoslangerak** [c0c0n3/ome-smuggler#1]
It would be useful to a client to put together potentially unrelated images into a single import session.
That way the user would get a single e-mail notification for all the files. Currently he receives an e-mail for every single file he imports. That can be potentially an annoyance to the user.

Alternatively users might prefer single e-mails.

Could it be configurable? setup a more sophisticated mechanism?

**Comment by c0c0n3** [comment]
The new import batch functionality allows Smuggler's clients to submit multiple images at once. (Available in master since commit de5afc78324f7571352e15663bd42f469e8a475a.) 

In more detail: a client can post one or more import requests in correspondence of each image to import. The posted requests are grouped in an import batch and each of them results in a separate invocation of the OMERO CLI importer, so it's entirely up to the client to decide which images go into the batch---in particular, it's possible to group unrelated images in a single batch. Also, the client can decide how many OMERO sessions to use---typically all the requests in the batch would share the same session, but each request is allowed to have its own. After all the requests in the batch have been processed (this includes retries), the user gets a single report email. (Currently Smuggler blindly assumes all import requests share the same email address, but we can easily lift this restriction if it turns out to be useful to batch import requests from different users.) If the user would like to get a separate email for each image, then the client should post one request at a time. Again, it's entirely up to the client what to do.
